### ISSUE TITLE
Cross-link with awesome-web-archiving?

### ISSUE THREAD

**Issue by anjackson** [DocNow/awesome-archive-tools#1]
I'm also involved with the [awesome list for web archiving](https://github.com/iipc/awesome-web-archiving) and [this pull request about Slack exports](https://github.com/iipc/awesome-web-archiving/pull/67) turned up. We decided it was out of scope, but recognised is a grey area.

Perhaps this is a place where these two Awesome Lists should cross-reference each other appropriately, so people who turn up on one can find their way to the other if that's appropriate?

Not sure how to do it though!?

**Comment by edsu** [comment]
Thanks for the heads up about this. Please feel free to refer them here, where is definitely in scope.
